issues:
  exclude-rules:
    - text: "G104: Errors unhandled"
      linters:
        - gosec
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - cyclop
    - deadcode
    - goconst
    - godot
    - godox
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 16
