version: "2.4"

services:
  db:
    image: postgres:13.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

  debug-db:
    image: dencold/pgcli
    environment:
      DB_URL: $DB_URL
    networks:
      - postgres_net

  migration:
    image: migrate/migrate
    entrypoint: migrate create -ext sql -dir /migration -seq
    volumes:
      - ./res/migration:/migration
    networks:
      - postgres_net

  version:
    image: migrate/migrate
    command: -path /migration -database $DB_URL version
    volumes:
      - ./res/migration:/migration
    networks:
      - postgres_net

  up:
    image: migrate/migrate
    entrypoint: migrate -path /migration -verbose -database $DB_URL up
    volumes:
      - ./res/migration:/migration
    networks:
      - postgres_net

  down:
    image: migrate/migrate
    entrypoint: migrate -path /migration -verbose -database $DB_URL down
    volumes:
      - ./res/migration:/migration
    networks:
      - postgres_net

  # A migration script can fail because of invalid syntax in sql files. http://bit.ly/2HQHx5s
  force:
    image: migrate/migrate
    entrypoint: migrate -path /migration -verbose -database $DB_URL force
    volumes:
      - ./res/migration:/migration
    networks:
      - postgres_net

volumes:
  postgres_data:

networks:
  postgres_net:
