apiVersion : apps/v1
kind: Deployment
metadata:
  name: employeeservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeeservice
  template:
    metadata:
      labels:
        app: employeeservice 
    spec:
      containers:
        - name: employeeservice 
          image: devpielabsregistry.azurecr.io/employeeservice
          ports:
          - containerPort: 8080