global:
  scrape_interval:     15s
  evaluation_interval: 15s

# define where prometheus get its data
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: employee-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8080